.\" Process this file with
.\" groff -man -Tascii mpi2prv.1
.\"
.TH MPI2PRV 1 "MAY 2010"
.SH NAME
mpi2prv \- MPI merge facility for the Paraver visualizer tool

mpi2dim \- MPI merge facility for the Dimemas simulation tool

mpimpi2prv \- Parallel MPI merge facility for the Paraver visualizer tool

mpimpi2dim \- Parallel MPI merge facility for the Dimemas simulation tool

.\"
.\" Com va?
.\" 
.SH SYNOPSIS
.B mpi2prv [-h] inputfile1 ... [--] inputfileN [-o <outputfile>]

.B mpi2dim [-h] inputfile1 ... [--] inputfileN [-o <outputfile>]

.B mpirun ... mpimpi2prv [-h] inputfile1 ... [--] inputfileN [-o <outputfile>]

.B mpirun ... mpimpi2dim [-h] inputfile1 ... [--] inputfileN [-o <outputfile>]

.\"
.\" Descripcio
.\"
.SH DESCRIPTION
.B mpi2prv
and
.B mpi2dim
are two different utilities to generate traces from the intermediate files written by the Extrae instrumentation tool.
.B mpi2prv
is responsible of the creation of Paraver traces whereas
.B mpi2dim
will generate Dimemsa traces.
The (Paraver and Dimemas) merge process  usually takes several *mpit files and produces a reduced set of files depending of the desired output. For Paraver traces (mpi2prv) the merge process will generate .prv(.gz), .pcf and .row while for Dimemas traces (mpi2dim) the merge process will generate .dim, .pcf and .row files.
If the machine supports MPI application then parallel version of these merger will also be available (
.B mpimpi2prv
and
.B mpimpi2dim
).
.\"
.\" Opcions
.\"
.SH OPTIONS
.IP "--"
This options marks that the next trace file should be considererd as a different parallel task.
.IP "-block"
MPIT files will be distributed in a block fashion instead of a cyclic fashion to the parallel Paraver merger.

.B Only valid for mpimpi2prv.
.IP "-cyclic"
MPIT files will be distributed in a cyclic fashion instead of a block fashion to the parallel Paraver merger.

.B Only valid for mpimpi2prv.
.IP "-size"
MPIT files will be distributed by size in the parallel Paraver merger.

.B Only valid for mpimpi2prv.
.IP "-consecutive-size"
MPIT files will be distributed by size but preserving the given order in the parallel Paraver merger.

.B Only valid for mpimpi2prv.
.IP "-d"
Sequentially dumps the contents of every intermediate file. This is very useful for debugging purposes, otherway it is useless.
.IP "-dimemas"
Forces the generation of a Dimemas tracefile regardless the information contained on the intermediate trace files. Be careful when using this option because timing will NOT be accurate.
.IP "-e file"
If the intermediate file contains information about MPI callers, -e will search on
.B file
 (which corresponds to the MPI application) in order to obtain information (function name, source file and line) of that caller. The application must be compiled with -g flag so as to obtain all the details for the callers.
.IP "-extended-glop-info"
Each global operation (MPI_Barrier, MPI_Alltoall, MPI_Reduce...) will generate additional information records on the tracefile. Such information usually contains: size of the global operation, who was the master and the communicator used.
.IP "-f file"
The mpitrace facility generates a *.mpits file with information of all intermediate files generated by a run. This 
.B file
can be used instead of giving the merger several parameters. This feature can be useful when many intermediate files are generated and the shell is not able to handle such quantity of parameters.
 This option looks first for each file listed in the parameter file. Each contained file is searched in the absolute given path, if it does not exist, then it's searched in the current directory.
.IP "-f-relative file"
This option works similarly as the 
.B -f
option, but it uses the current path to locate the listed files.
.IP "-f-absolute file"
This option behaves similarly than
.B -f 
option, but it uses the full path of every intermediate file so as to locate the listed files.
.IP "-h"
Gets a simple help text.
.IP "-o file"
.B file
determines which must be the output filename for the merged Paraver tracefile. If the file exists, it will be overwritten. mpi2prv can also deal directly with compressed files (via libz). In order to generate a compressed tracefile, simply add .prv.gz to the extension of the output filename instead of .prv. Note, however, that mpi2dim cannot generate compressed files.
.IP "-paraver"
Forces the generation of a Paraver tracefile regardless the information contained on the intermediate trace files. Be careful when using this option because timing will NOT be accurate.
.IP "-s file"
.B file
indicates the symbol file attached to the *.mpit files. It is a good place to put some information of the manually added events.
.IP "-split-states"
Do not join consecutive states that are the same into a single one.
.IP "-syn"
If different nodes are used in the execution of a tracing run, there can exist some clock differences on all the nodes. This option makes mpi2prv to recalculate all the timings based on the end of the MPI_Init call. This will usually lead to "synchronized" tasks, but it will depend on how the clocks advance in time.

It is not a perfect solution where all the clocks are different, but can give a first impression on how the run worked.

.B Only affects to Paraver traces. Use with caution. mpi2prv uses a simple but effective method to determine if this option must be applied.
.IP "-syn-node"
If different nodes are used in the execution of a tracing run, there can exist some clock differences on all the nodes. This option makes mpi2prv to recalculate all the timings based on the end of the MPI_Init call and the node where they ran. This will usually lead to better synchronized tasks than using -syn, but, again, it will depend on how the clocks advance in time.

As with -syn it is not a perfect solution.

.B Only affects to Paraver traces. Use with caution. mpi2prv uses a simple but effective method to determine if this option must be applied.
.IP "-no-syn"
If set, the merger will not attempt to synchronize the different tasks. This is useful when merging intermediate files obtained from a single node (and thus, share a single clock).

.B Only affects to Paraver traces. Use with caution. mpi2prv uses a simple but effective method to determine if this option must be applied.
.IP "-xyzt"
On the BG/L system each task can be mapped in different points of a torus network. This option will produce a file with the coordinates on the network of each task.
.\"
.\" Environment variables
.\"
.SH ENVIRONMENT
This section describes all the environment variables related to the merging process.
.IP "EXTRAE_LABELS"
This environment variable lets the user add custom information to the generated Paraver Configuration File (.pcf). Just set this variable to point to a file containing labels for the unknown (user) events.
The format for the file is:

  EVENT_TYPE
  0 [type1] [label1]
  0 [type2] [label2]
  ...
  0 [typeK] [labelK]

Where [typeN] is the event value and [labelN] is the description for the event with value [typeN].
It is also possible to link both type and value of an event:

  EVENT_TYPE
  0 [type] [label]
  VALUES
  [value1] [label1]
  [value2] [label2]
  ...
  [valueN] [labelN]

With this information, Paraver can deal with both type and  value when giving textual information to the end user. If Paraver does not find any information for an event/type it will shown it in numerical form.
.IP "MPI2PRV_TMP_DIR"
Points to a directory where all intermediate temporary files will be stored. These files will be removed as soon the application ends.
.\"
.\" Exemples 
.\"
.SH EXAMPLES
To merge all the intermediate files into a Paraver trace file, simply type:

mpi2prv *.mpit -o out.prv

However, to generate a Dimemas trace file, type:

mpi2dim *.mpit -o out.dim

If the Paraver tracefile must be compressed (so as to save disk space) use:

mpi2prv *.mpit -o out.prv.gz

If the intermediate files are generated on different nodes, some clock synchronization can be interesting:

mpi2prv -syn *.mpit -o out.prv.gz

If the Paraver tracefile must contain additional information about MPI global operations and information about the MPI calls, then use:

mpi2prv -syn -extended-glop-info -e ./program -syn -o out.prv.gz
.\"
.\" Informacio d'autor
.\"
.SH AUTHOR
Tool was developed at the CEPBA (European Center for Parallelism of Barcelona) and at the BSC (Barcelona Supercomputing Center) by the "tools team".

This online documentation was written by Harald Servat Gelabert
.\"
.\" Com reportar bugs
.\"
.SH "REPORTING BUGS"
If you find any bug on the documentation or in the software, please send a descriptive mail to

.B tools@bsc.es
.\"
.\" D'on treure mes informacio
.\"
.SH "ONLINE DOCUMENTATION"
More information and detailed examples can be found at

.B http://www.bsc.es/paraver
.\"
.\" Altres
.\"
.SH "SEE ALSO"
.BR extrae (1)

.BR extrae_event (3)
.BR extrae_counters (3)
.BR extrae_eventandcounters (3)
.BR extrae_shutdown (3)
.BR extrae_restart (3)
.BR extrae_set_tracing_tasks (3)
.BR extrae_set_options (3)
