.\" Process this file with
.\" groff -man -Tascii UFlist.1
.\"
.TH UFLIST 1 "MAY 2010"

.SH NAME
UFlist.sh \- Obtain user function information of one binary file.

.\"
.\" Com va?
.\" 
.SH SYNOPSIS
.B UFlist.sh <application-binary>
.\"
.\" Descripcio
.\"
.SH DESCRIPTION
.B UFlist.sh 
will echo the available routines that can be found in the text section of a binary with their corresponding address. Such output can be used as input for the Extrae package (EXTRAE_FUNCTIONS environment variable) in order to trace a selected set of user functions.
Instrumenting routines 
.B requires
the source files to be compiled with GCC and with -finstrument-functions.
Be careful that
.B only source files that are compiled with -finstrument-functions are able to be trace.
The output is given in the standard form that Extrae wants the file pointed by EXTRAE_FUNCTIONS. I.e., on pair address # routine per line.
.\"
.\" Opcions
.\"
.SH OPTIONS
.IP "filename"
UFlist.sh will analyze this file.
.\"
.\" Environment variables
.\"
.SH ENVIRONMENT
This section describes all the environment variables related to the mpi2prv merging process.
.IP "TMPDIR"
Where all the temporal files will be store temporally ($PWD if $TMPDIR is not defined).
.\"
.\" Informacio d'autor
.\"
.SH AUTHOR
Tool was developed at the CEPBA (European Center for Parallelism of Barcelona) and at the BSC (Barcelona Supercomputing Center) by the "tools team".

This online documentation was written by Harald Servat Gelabert
.\"
.\" Com reportar bugs
.\"
.SH "REPORTING BUGS"
If you find any bug on the documentation or in the software, please send a descriptive mail to

.B tools@bsc.es
.\"
.\" D'on treure mes informacio
.\"
.SH "ONLINE DOCUMENTATION"
More information and detailed examples can be found at

.B http://www.bsc.es/paraver
.\"
.\" Altres
.\"
.SH "SEE ALSO"
.BR mpi2prv (1)

.BR mpitrace_event (3)
.BR mpitrace_counters (3)
.BR mpitrace_eventandcounters (3)
.BR mpitrace_shutdown (3)
.BR mpitrace_restart (3)
.BR mpitrace_set_tracing_tasks (3)
.BR mpitrace_set_options (3)
