#!/bin/sh

libtoolize --automake --force --copy \
&& aclocal -I config \
&& autoheader \
&& automake --gnu --add-missing --copy \
&& autoconf

if test `basename ${0}` = "bootstrap-and-dist" ; then
	./configure --without-mpi --without-papi --without-dyninst --without-unwind --without-binutils
	make dist-bzip2
fi
