#!/bin/bash
#
# This file is automatically generated by the MPItrace instrumentation Makefile.
# DO NOT EDIT!
#

if test "${EXTRAE_HOME}" != "" ; then
	if test -d ${EXTRAE_HOME} ; then
		echo "EXTRAE_HOME points to ${EXTRAE_HOME} and the directory exists .. OK"
	else
		echo "EXTRAE_HOME points to ${EXTRAE_HOME} and the directory does NOT exist .. FAILED"
	fi
else
	echo "EXTRAE_HOME is undefined... Cannot proceed much more!"
	echo "Please, define EXTRAE_HOME environment variable to a MPItrace package installation"
fi

if test "${EXTRAE_HOME}" != "" ; then

	# Read configuration variables if available!
	if ! test -f ${EXTRAE_HOME}/etc/extrae-vars.sh ; then
		echo "Error! Unable to locate ${EXTRAE_HOME}/etc/extrae-vars.sh"
		echo "Dying..."
		exit 
	else
		echo
		source ${EXTRAE_HOME}/etc/extrae-vars.sh
		echo "Loaded specs for ${PACKAGE_NAME:-MPItrace} from ${EXTRAE_HOME}/etc/extrae-vars.sh"
	fi

	echo
	echo ${PACKAGE_NAME} was configured with:
	echo ${CONFIGURE_LINE}
	echo

	if test "${MPI_HOME}" != "" ; then
		if test -d ${MPI_HOME} ; then
			echo "MPI_HOME points to ${MPI_HOME} and the directory exists .. OK"
		else
			echo "MPI_HOME points to ${MPI_HOME} and the directory does NOT exist .. FAILED"
		fi
	else
		echo "MPI support seems to be disabled"
	fi

	if test "${PACX_HOME}" != "" ; then
		if test -d ${MPI_HOME} ; then
			echo "PACX_HOME points to ${PACX_HOME} and the directory exists .. OK"
		else
			echo "PACX_HOME points to ${PACX_HOME} and the directory does NOT exist .. FAILED"
		fi
	else
		echo "PACX support seems to be disabled"
	fi

	if test "${LIBXML2_HOME}" != "" ; then
		if test -d ${LIBXML2_HOME} ; then
			echo "LIBXML2_HOME points to ${LIBXML2_HOME} and the directory exists .. OK"
		else
			echo "LIBXML2_HOME points to ${LIBXML2_HOME} and the directory does NOT exist .. FAILED"
		fi
	else
		echo "XML support seems to be disabled"
	fi

	if test "${PAPI_HOME}" != "" ; then
		if test -d ${PAPI_HOME} ; then
			echo "PAPI_HOME points to ${PAPI_HOME} and the directory exists .. OK"
		else
			echo "PAPI_HOME points to ${PAPI_HOME} and the directory does NOT exist .. FAILED"
		fi
	else
		echo "PAPI support seems to be disabled"
	fi

	if test "${DYNINST_HOME}" != "" ; then
		if test -d ${DYNINST_HOME} ; then
			echo "DYNINST_HOME points to ${DYNINST_HOME} and the directory exists .. OK"
		else
			echo "DYNINST_HOME points to ${DYNINST_HOME} and the directory does NOT exist .. FAILED"
		fi
	else
		echo "DYNINST support seems to be disabled"
	fi
fi

echo 
echo "Please, report bugs to ${PACKAGE_BUGREPORT:-tools@bsc.es}"

