#
# This file is automatically generated by the Extrae instrumentation Makefile.
# Edit with caution
#

if [[ -z ${EXTRAE_HOME} ]]; then
    export EXTRAE_HOME=@sub_PREFIXDIR@
fi

# Read configuration variables if available!
if [[ -f ${EXTRAE_HOME}/etc/extrae-vars.sh ]] ; then
	. ${EXTRAE_HOME}/etc/extrae-vars.sh
else
	echo "Error! Unable to locate ${EXTRAE_HOME}/etc/extrae-vars.sh"
	echo "Dying..."
	exit
fi

if [[ -f "${EXTRAE_ONLINE_SOURCES}" ]] ; then
	. ${EXTRAE_ONLINE_SOURCES}
fi

export PYTHONPATH=${EXTRAE_HOME}/libexec:${PYTHONPATH}

export LD_LIBRARY_PATH=${EXTRAE_HOME}/lib:${EXTRAE_MPI_LIBSDIR}:${EXTRAE_PAPI_LIBSDIR}:${EXTRAE_LIBXML2_LIBSDIR}:${EXTRAE_DYNINST_LIBSDIR}:${EXTRAE_DWARF_LIBSDIR}:${EXTRAE_ELF_LIBSDIR}:${EXTRAE_LIBERTY_LIBSDIR}:${EXTRAE_BFD_LIBSDIR}:${EXTRAE_UNWIND_LIBSDIR}:${EXTRAE_BOOST_LIBSDIR}:${LD_LIBRARY_PATH}

