#ifndef _gm_inline_h_
#define _gm_inline_h_

#include "_gm_user_ioctl.c"
#include "gm_alloc_send_token.c"
#include "gm_bcopy.c"
#include "gm_bzero.c"
#include "gm_put.c"
#include "gm_flush_alarm.c"
#include "gm_free_send_token.c"
#include "gm_free_send_tokens.c"
#include "gm_get_global_id.c"
#include "gm_get_unique_board_id.c"
#include "gm_hostname_to_global_id.c"
#include "gm_max_global_id.c"
#include "gm_max_global_id_inuse.c"
#include "gm_memorize_message.c"
#include "gm_next_event_peek.c"
#include "gm_ethernet_provide_scatter_list.c"
#include "gm_provide_raw_receive_buffer.c"
#include "gm_provide_receive_buffer.c"
#include "gm_raw_send.c"
#include "gm_receive_pending.c"
#include "gm_recv_event_type.c"
#include "gm_retry_send.c"
#include "gm_send.c"
#include "gm_send_to_peer.c"
#include "gm_send_token_available.c"
#include "gm_set_acceptable_sizes.c"
#include "gm_set_alarm.c"
#include "gm_set_global_id.c"

#endif /* ifndef _gm_inline_h_ */
